version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/todayoutfit/
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/todayoutfit/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user